name: helix
version: 1.0.0
description: AI-assisted iterative development workflow with human-AI collaboration
author: DDX Team
created: 2025-01-13
tags:
  - ai-assisted-development
  - iterative
  - human-ai-collaboration

variables:
  - name: project_name
    description: Name of the project
    prompt: What is your project name?
    required: true

phases:
  - id: frame
    order: 1
    name: Frame the Problem
    description: Define and analyze the problem with AI assistance
    required_role: architect
    exit_criteria:
      - Problem statement clearly documented
      - Success metrics defined
      - Constraints and requirements captured
      - Context established for AI agents
    estimated_duration: 1-2 days

  - id: design
    order: 2
    name: Design the Solution
    description: Architect the solution with AI collaboration
    required_role: architect
    exit_criteria:
      - System architecture documented
      - Technology choices justified
      - Design patterns selected
      - Approach validated
    estimated_duration: 1-2 days

  - id: test
    order: 3
    name: Write Tests First
    description: Define system behavior through comprehensive test suites before implementation
    required_role: test-engineer
    exit_criteria:
      - All contract tests written (failing)
      - Integration tests defined (failing)
      - Unit test stubs created (failing)
      - Test coverage plan approved
    estimated_duration: 2-3 days

  - id: build
    order: 4
    name: Build to Pass Tests
    description: Implement code using TDD to make all tests pass
    required_role: developer
    exit_criteria:
      - All tests passing (green)
      - Code coverage targets met
      - Code reviewed and refactored
      - Documentation generated
    estimated_duration: variable

  - id: deploy
    order: 5
    name: Deploy the System
    description: Deploy with AI-guided DevOps
    required_role: devops-engineer
    exit_criteria:
      - Successfully deployed
      - Monitoring configured
      - Documentation published
      - Deployment verified
    estimated_duration: 1 day

  - id: iterate
    order: 6
    name: Iterate the Process
    description: Gather feedback and improve with AI analysis
    required_role: analyst
    exit_criteria:
      - Feedback analyzed
      - Improvements identified
      - Next iteration planned
      - Learnings captured
    estimated_duration: ongoing