library_path: ../ddx/library
includes:
    - prompts/claude
    - scripts/hooks
    - templates/common
    - patterns/error-handling
overrides: {}
persona_bindings:
    analyst: analyst-feedback
    architect: architect-systems
    code-reviewer: strict-code-reviewer
    developer: developer-senior-golang
    devops-engineer: devops-engineer-kubernetes
    test-engineer: test-engineer-tdd
    workflow-coordinator: helix-workflow-enforcer
preferences:
    auto_apply_hooks: true
    backup_before_update: true
    check_updates: true
repository:
    branch: main
    path: .ddx/
    url: https://github.com/easel/ddx
subtree:
    auto_update: false
    contribution_branch: contributions
    enabled: true
variables:
    ai_model: claude-3-opus
    architecture_description: CLI application with Cobra framework, Tugboat Logic API integration, and AI-powered evidence collection
    auth_choice: Browser-based OAuth with Tugboat Logic
    build_command: make build
    config_directory: internal/config
    database_choice: Local JSON storage with Tugboat API sync
    format_command: make fmt
    key_components: CLI commands, Tugboat API client, Evidence collection tools, AI integration, Storage layer
    key_patterns: Error handling, structured logging, table-driven testing, interface segregation
    lint_command: make lint
    main_directory: internal
    project_description: GRCTool - Automated compliance evidence collection CLI for SOC2 and ISO27001
    project_name: grctool
    tech_stack: Go 1.23+, Cobra CLI, Claude AI API, Tugboat Logic API
    test_command: make test
version: 1