name: Security Requirements
description: Comprehensive security requirements definition for the project
category: security
phase: 01-frame
priority: high
type: template

dependencies:
  artifacts:
    - prd
    - user-stories
  external:
    - business_requirements
    - compliance_policies

output:
  location: docs/helix/01-frame/security-requirements.md
  format: markdown

variables:
  required:
    - project_name
    - project_type
    - data_types
    - compliance_requirements
    - deployment_environment
  optional:
    - industry_sector
    - geographic_scope
    - risk_tolerance
    - existing_security_controls

validation_rules:
  required_sections:
    - security_user_stories
    - compliance_requirements
    - risk_assessment
    - acceptance_criteria
  quality_checks:
    - all_requirements_have_acceptance_criteria
    - compliance_requirements_mapped
    - risk_levels_defined
    - testable_criteria_specified

automation:
  triggers:
    - prd_completed
    - user_stories_defined
  tools:
    - security_scanning_setup
    - compliance_checking

workflow_integration:
  input_gates:
    - business_requirements_defined
    - stakeholder_alignment_complete
  exit_gates:
    - security_requirements_approved
    - compliance_mapping_complete
    - security_champion_signoff
  next_phase_inputs:
    - security_architecture_requirements
    - security_design_constraints
    - security_testing_strategy

ai_assistance:
  prompt_file: prompt.md
  capabilities:
    - requirement_generation
    - compliance_mapping
    - risk_analysis
    - requirement_validation
  specialization: security_requirements_analyst

collaboration:
  stakeholders:
    - product_owner
    - security_champion
    - compliance_officer
    - technical_lead
  approval_required:
    - product_owner
    - security_champion
  review_cycle: iterative

documentation:
  template_file: template.md
  examples_available: true
  best_practices_guide: ../../../docs/security-integration-guide.md

metrics:
  completeness:
    - requirements_coverage_percentage
    - compliance_requirements_mapped
    - acceptance_criteria_defined
  quality:
    - requirements_testability_score
    - business_alignment_score
    - implementation_feasibility_score