// Copyright 2024 GRCTool Authors
// SPDX-License-Identifier: Apache-2.0

package evidence

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/grctool/grctool/internal/domain"
	"github.com/grctool/grctool/internal/logger"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func newTestLogger(t *testing.T) logger.Logger {
	t.Helper()
	log, err := logger.NewTestLogger()
	require.NoError(t, err)
	return log
}

func TestNewSimpleOutputGenerator(t *testing.T) {
	t.Parallel()
	log := newTestLogger(t)
	gen := NewSimpleOutputGenerator("/tmp/data", log)
	assert.NotNil(t, gen)
	assert.Equal(t, "/tmp/data", gen.dataDir)
}

func TestGenerateSimpleEvidence_Basic(t *testing.T) {
	t.Parallel()
	log := newTestLogger(t)
	gen := NewSimpleOutputGenerator("/tmp/data", log)

	task := &domain.EvidenceTask{
		ReferenceID: "ET-0001",
		Name:        "GitHub Repository Access Controls",
		Description: "Verify team permissions for all repositories.",
	}

	tasks := []CollectionTask{
		{
			Number:      1,
			Description: "Collect repository permissions",
			Evidence:    "Teams and access levels documented.",
			Snippets: []EvidenceSnippet{
				{
					Content:    "Team: Engineering\nAccess: Write",
					SourceFile: "permissions.json",
					OriginalPath: "docs/evidence/permissions.json",
					LastModified: time.Date(2025, 1, 1, 0, 0, 0, 0, time.UTC),
					Section:     "Repository Access",
				},
			},
		},
	}

	result, err := gen.GenerateSimpleEvidence(task, "Q1 2025", tasks)
	require.NoError(t, err)

	assert.Contains(t, result, "# ET-0001: GitHub Repository Access Controls")
	assert.Contains(t, result, "**Task Description:**")
	assert.Contains(t, result, "**Collection Window:** Q1 2025")
	assert.Contains(t, result, "## Collection Task 1: Collect repository permissions")
	assert.Contains(t, result, "**Evidence:** Teams and access levels documented.")
	assert.Contains(t, result, "**Source:** `permissions.json`")
	assert.Contains(t, result, "**Original Path:** `docs/evidence/permissions.json`")
	assert.Contains(t, result, "**Section:** Repository Access")
	assert.Contains(t, result, "> Team: Engineering")
}

func TestGenerateSimpleEvidence_WithGeneratedSnippet(t *testing.T) {
	t.Parallel()
	log := newTestLogger(t)
	gen := NewSimpleOutputGenerator("/tmp/data", log)

	task := &domain.EvidenceTask{
		ReferenceID: "ET-0002",
		Name:        "Terraform Config",
		Description: "Review Terraform.",
	}

	collectionDate := time.Date(2025, 3, 1, 0, 0, 0, 0, time.UTC)
	tasks := []CollectionTask{
		{
			Number:      1,
			Description: "Generated evidence",
			Snippets: []EvidenceSnippet{
				{
					Content:        "resource aws_iam_role {...}",
					SourceFile:     "terraform_scan.json",
					GeneratedBy:    "grctool tool terraform-security-analyzer",
					CollectionDate: collectionDate,
				},
			},
		},
	}

	result, err := gen.GenerateSimpleEvidence(task, "", tasks)
	require.NoError(t, err)

	assert.Contains(t, result, "**Generated By:** `grctool tool terraform-security-analyzer`")
	assert.Contains(t, result, "**Collection Date:** 2025-03-01")
	assert.NotContains(t, result, "Collection Window")
}

func TestGenerateSimpleEvidence_NoTasks(t *testing.T) {
	t.Parallel()
	log := newTestLogger(t)
	gen := NewSimpleOutputGenerator("/tmp/data", log)

	task := &domain.EvidenceTask{
		ReferenceID: "ET-0003",
		Name:        "Empty Task",
		Description: "No collection tasks.",
	}

	result, err := gen.GenerateSimpleEvidence(task, "", nil)
	require.NoError(t, err)
	assert.Contains(t, result, "# ET-0003: Empty Task")
}

func TestMakeRelativePath_InsideDataDir(t *testing.T) {
	t.Parallel()
	log := newTestLogger(t)
	gen := NewSimpleOutputGenerator("/home/user/data", log)

	rel, err := gen.MakeRelativePath("/home/user/data/docs/policies/pol1.json")
	require.NoError(t, err)
	assert.Equal(t, filepath.Join("docs", "policies", "pol1.json"), rel)
}

func TestMakeRelativePath_OutsideDataDir(t *testing.T) {
	t.Parallel()
	log := newTestLogger(t)
	gen := NewSimpleOutputGenerator("/home/user/data", log)

	rel, err := gen.MakeRelativePath("/etc/config/something.json")
	require.NoError(t, err)
	assert.Equal(t, "/etc/config/something.json", rel)
}

func TestGetSourceMetadata(t *testing.T) {
	t.Parallel()
	tmpDir := t.TempDir()
	log := newTestLogger(t)
	gen := NewSimpleOutputGenerator(tmpDir, log)

	testFile := filepath.Join(tmpDir, "test.json")
	require.NoError(t, os.WriteFile(testFile, []byte(`{"test": true}`), 0644))

	meta, err := gen.GetSourceMetadata(testFile)
	require.NoError(t, err)
	assert.Equal(t, testFile, meta.OriginalPath)
	assert.Equal(t, "test.json", meta.DestFilename)
	assert.Equal(t, "test.json", meta.RelativePath)
	assert.False(t, meta.LastModified.IsZero())
}

func TestGetSourceMetadata_NotFound(t *testing.T) {
	t.Parallel()
	log := newTestLogger(t)
	gen := NewSimpleOutputGenerator("/tmp", log)

	_, err := gen.GetSourceMetadata("/nonexistent/file.json")
	require.Error(t, err)
}

func TestCopySourceFilesFlat(t *testing.T) {
	t.Parallel()
	tmpDir := t.TempDir()
	srcDir := filepath.Join(tmpDir, "src")
	destDir := filepath.Join(tmpDir, "dest")
	require.NoError(t, os.MkdirAll(srcDir, 0755))

	srcFile := filepath.Join(srcDir, "original.txt")
	require.NoError(t, os.WriteFile(srcFile, []byte("hello world"), 0644))

	log := newTestLogger(t)
	gen := NewSimpleOutputGenerator(tmpDir, log)

	sources := []SourceFile{
		{
			OriginalPath: srcFile,
			RelativePath: "src/original.txt",
			DestFilename: "copied.txt",
		},
	}

	err := gen.CopySourceFilesFlat(sources, destDir)
	require.NoError(t, err)

	data, err := os.ReadFile(filepath.Join(destDir, "copied.txt"))
	require.NoError(t, err)
	assert.Equal(t, "hello world", string(data))
}

func TestCopySourceFilesFlat_MissingSource(t *testing.T) {
	t.Parallel()
	tmpDir := t.TempDir()
	destDir := filepath.Join(tmpDir, "dest")

	log := newTestLogger(t)
	gen := NewSimpleOutputGenerator(tmpDir, log)

	sources := []SourceFile{
		{
			OriginalPath: "/nonexistent/file.txt",
			DestFilename: "missing.txt",
		},
	}

	// Should not error, just skip missing files
	err := gen.CopySourceFilesFlat(sources, destDir)
	require.NoError(t, err)
	// The dest file should not exist
	_, err = os.Stat(filepath.Join(destDir, "missing.txt"))
	assert.True(t, os.IsNotExist(err))
}

func TestFormatAsMarkdownQuote(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name     string
		input    string
		expected string
	}{
		{
			name:     "single line",
			input:    "Hello world",
			expected: "> Hello world\n",
		},
		{
			name:     "multi line",
			input:    "Line 1\nLine 2\nLine 3",
			expected: "> Line 1\n> Line 2\n> Line 3\n",
		},
		{
			name:     "empty string",
			input:    "",
			expected: "> \n",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()
			result := FormatAsMarkdownQuote(tt.input)
			assert.Equal(t, tt.expected, result)
		})
	}
}

func TestBreakdownIntoCollectionTasks(t *testing.T) {
	t.Parallel()
	log := newTestLogger(t)
	gen := NewSimpleOutputGenerator("/tmp/data", log)

	t.Run("basic task", func(t *testing.T) {
		t.Parallel()
		task := &domain.EvidenceTask{
			Name:        "Test Task",
			Description: "",
			Controls:    nil,
		}
		tasks, err := gen.BreakdownIntoCollectionTasks(task)
		require.NoError(t, err)
		assert.Len(t, tasks, 1)
		assert.Contains(t, tasks[0], "Test Task")
	})

	t.Run("task with description and controls", func(t *testing.T) {
		t.Parallel()
		task := &domain.EvidenceTask{
			Name:        "GitHub Access",
			Description: "Check permissions",
			Controls:    []string{"CC6.1", "CC6.2"},
		}
		tasks, err := gen.BreakdownIntoCollectionTasks(task)
		require.NoError(t, err)
		assert.Len(t, tasks, 3)
	})
}

func TestExtractRelevantSnippets(t *testing.T) {
	t.Parallel()
	log := newTestLogger(t)
	gen := NewSimpleOutputGenerator("/tmp/data", log)

	snippet := gen.ExtractRelevantSnippets(
		"content here",
		"source.json",
		"docs/source.json",
		"Section 1",
	)

	assert.Equal(t, "content here", snippet.Content)
	assert.Equal(t, "source.json", snippet.SourceFile)
	assert.Equal(t, "docs/source.json", snippet.OriginalPath)
	assert.Equal(t, "Section 1", snippet.Section)
	assert.False(t, snippet.LastModified.IsZero())

	// Verify the content round-trips through markdown quote
	quoted := FormatAsMarkdownQuote(snippet.Content)
	assert.True(t, strings.HasPrefix(quoted, "> "))
}
