name: Security Vulnerability (Use with Caution)
description: Report a security vulnerability - PLEASE READ SECURITY.md FIRST
title: "[SECURITY]: "
labels: ["security", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## ⚠️ IMPORTANT: Private Disclosure Preferred

        **For serious security vulnerabilities, please DO NOT use this public issue tracker.**

        Instead, please follow our responsible disclosure process:
        1. Review [SECURITY.md](https://github.com/grctool/grctool/blob/main/SECURITY.md)
        2. Email security@grctool.dev (preferred for sensitive issues)
        3. Allow us time to fix the issue before public disclosure

        **Only use this template for:**
        - Low-severity security concerns
        - Security-related questions or best practice discussions
        - Already-public vulnerabilities in dependencies
        - Security feature requests

  - type: checkboxes
    id: acknowledgment
    attributes:
      label: Security Disclosure Acknowledgment
      description: Please confirm you understand the security reporting guidelines
      options:
        - label: I have read SECURITY.md and understand the responsible disclosure process
          required: true
        - label: This is NOT a critical or high-severity vulnerability requiring private disclosure
          required: true
        - label: I understand this issue will be publicly visible immediately
          required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity Level
      description: What is the severity of this security concern?
      options:
        - Informational - Security question or discussion
        - Low - Minor security improvement suggestion
        - Dependency - Public vulnerability in third-party dependency
        - Other - Please explain
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Security Concern Description
      description: Describe the security-related issue or question
      placeholder: |
        Describe the security concern...
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: Potential Impact
      description: |
        What is the potential security impact?
        Who or what could be affected?
      placeholder: |
        Impact:
        - ...
        - ...

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce (if applicable)
      description: |
        How can this security concern be demonstrated?
        DO NOT include actual exploit code for high-severity issues.
      placeholder: |
        1.
        2.
        3.

  - type: textarea
    id: mitigation
    attributes:
      label: Suggested Mitigation
      description: |
        If you have suggestions for fixing or mitigating this issue, please share them.
      placeholder: |
        Potential fixes:
        - ...
        - ...

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: |
        Any additional context about the security concern.
        References to CVEs, security advisories, etc.
      placeholder: |
        References:
        - ...
        - ...

  - type: checkboxes
    id: affected-versions
    attributes:
      label: Affected Versions
      description: Which versions are affected?
      options:
        - label: Latest release
        - label: Main branch
        - label: Specific version (please specify in additional context)
        - label: Unknown

  - type: markdown
    attributes:
      value: |
        ---

        ## 📧 Private Disclosure Reminder

        If you realize this issue is more serious than initially thought, please:
        1. **Do not submit this form**
        2. Email security@grctool.dev instead
        3. Wait for acknowledgment before any public disclosure

        Thank you for helping keep GRCTool secure!
