# Metadata for Product Requirements Document (PRD)

artifact:
  name: Product Requirements Document
  id: prd
  type: document
  phase: frame

description: |
  The PRD is the foundational business document that defines the problem,
  solution vision, success metrics, and requirements. It serves as the
  single source of truth for what we're building and why.

dependencies:
  requires:
    - input: Problem or opportunity identified
      type: external
      required: true
    - input: Stakeholder input gathered
      type: external
      required: true

  enables:
    - output: Feature specifications
      type: artifact
      path: feature-specification
    - output: User stories
      type: artifact
      path: user-stories
    - output: Solution design
      type: artifact
      phase: design

output:
  location: docs/helix/01-frame/prd.md
  format: markdown
  naming: prd.md

validation:
  required_sections:
    - executive_summary
    - problem_statement
    - goals_and_objectives
    - success_metrics
    - users_and_personas
    - requirements_overview
    - risks_and_mitigation
    - timeline_and_milestones

  quality_checks:
    - check: metrics_quantified
      description: All success metrics must have numeric targets
      severity: blocking

    - check: personas_validated
      description: User personas should be based on actual research
      severity: warning

    - check: requirements_prioritized
      description: Requirements must be categorized as P0/P1/P2
      severity: blocking

    - check: risks_mitigated
      description: Each risk must have a mitigation strategy
      severity: warning

  automated_checks:
    - pattern: "\\[NEEDS CLARIFICATION"
      expected: 0
      message: Remove all clarification markers before approval

    - pattern: "P0|Must Have"
      expected: ">0"
      message: PRD must define at least one P0 requirement

variables:
  - name: product_name
    description: Name of the product being developed
    required: true

  - name: target_launch_date
    description: Target date for product launch
    required: false

  - name: primary_stakeholder
    description: Primary stakeholder or product owner
    required: true

prompts:
  generation: prompt.md
  review: |
    Review this PRD for:
    1. Clarity of problem statement
    2. Measurability of success metrics
    3. Completeness of requirements
    4. Identification of risks
    5. Alignment with business goals

template:
  file: template.md
  sections:
    - executive_summary: "Write this last"
    - problem_statement: "Start here"
    - success_metrics: "Make specific and measurable"

examples:
  - file: example.md
    description: Sample PRD for a CLI development toolkit

workflow:
  creation_order: 1
  review_cycles: 2-3
  approval_required: true
  approvers:
    - Product Owner
    - Technical Lead
    - Key Stakeholders

relationships:
  informs:
    - principles
    - feature-specification
    - user-stories
    - feature-registry

  referenced_by:
    - solution-design
    - test-plan
    - deployment-checklist

tags:
  - business
  - requirements
  - vision
  - strategy

version: 1.0.0
last_updated: 2024-01-14