name: Threat Model
description: Systematic identification and analysis of security threats using STRIDE methodology
category: security
phase: 01-frame
priority: high
type: template

dependencies:
  artifacts:
    - prd
    - security-requirements
    - user-stories
  external:
    - system_architecture
    - data_flow_diagrams

output:
  location: docs/helix/01-frame/threat-model.md
  format: markdown

variables:
  required:
    - project_name
    - system_components
    - data_flows
    - trust_boundaries
    - external_interfaces
  optional:
    - threat_actors
    - existing_security_controls
    - risk_tolerance
    - compliance_requirements

validation_rules:
  required_sections:
    - system_description
    - stride_analysis
    - risk_assessment
    - mitigation_strategies
  quality_checks:
    - all_components_analyzed
    - stride_categories_complete
    - risk_scores_calculated
    - mitigations_defined

automation:
  triggers:
    - system_architecture_defined
    - security_requirements_complete
  tools:
    - threat_modeling_tools
    - risk_assessment_calculators

workflow_integration:
  input_gates:
    - system_boundaries_defined
    - security_requirements_approved
  exit_gates:
    - threat_model_reviewed
    - critical_threats_mitigated
    - security_champion_approval
  next_phase_inputs:
    - security_design_requirements
    - security_controls_specification
    - security_test_scenarios

ai_assistance:
  prompt_file: prompt.md
  capabilities:
    - stride_analysis
    - risk_assessment
    - threat_scenario_generation
    - mitigation_strategy_development
  specialization: cybersecurity_analyst

collaboration:
  stakeholders:
    - security_champion
    - technical_lead
    - product_owner
    - security_architect
  approval_required:
    - security_champion
    - technical_lead
  review_cycle: collaborative

documentation:
  template_file: template.md
  examples_available: true
  methodology_guide: stride_methodology.md

metrics:
  completeness:
    - components_analyzed_percentage
    - stride_categories_covered
    - threats_identified_count
  quality:
    - risk_assessment_accuracy
    - mitigation_feasibility_score
    - business_alignment_score