name: Compliance Requirements
description: Comprehensive regulatory and compliance requirements analysis
category: compliance
phase: 01-frame
priority: high
type: template

dependencies:
  artifacts:
    - prd
    - security-requirements
    - stakeholder-map
  external:
    - business_context
    - regulatory_landscape
    - legal_counsel_input

output:
  location: docs/helix/01-frame/compliance-requirements.md
  format: markdown

variables:
  required:
    - business_sector
    - operating_jurisdictions
    - data_types_processed
    - customer_types
    - deployment_locations
  optional:
    - company_size
    - public_private_status
    - existing_compliance_obligations
    - risk_tolerance

validation_rules:
  required_sections:
    - regulatory_landscape_analysis
    - compliance_requirements_matrix
    - data_classification
    - implementation_plan
  quality_checks:
    - all_applicable_regulations_identified
    - requirements_mapped_to_implementation
    - risk_assessment_completed
    - timeline_defined

automation:
  triggers:
    - business_context_defined
    - data_flows_documented
  tools:
    - compliance_scanning
    - regulatory_update_monitoring

workflow_integration:
  input_gates:
    - business_requirements_defined
    - data_classification_complete
  exit_gates:
    - compliance_requirements_approved
    - legal_review_complete
    - implementation_plan_approved
  next_phase_inputs:
    - compliance_design_constraints
    - security_controls_requirements
    - audit_requirements

ai_assistance:
  prompt_file: prompt.md
  capabilities:
    - regulatory_applicability_analysis
    - requirements_mapping
    - risk_assessment
    - implementation_planning
  specialization: compliance_specialist

collaboration:
  stakeholders:
    - compliance_officer
    - legal_counsel
    - product_owner
    - security_champion
  approval_required:
    - compliance_officer
    - legal_counsel
  review_cycle: iterative

documentation:
  template_file: template.md
  examples_available: true
  regulatory_guides: ../../../docs/compliance-guides/

metrics:
  completeness:
    - regulations_identified_count
    - requirements_mapped_percentage
    - implementation_plan_coverage
  quality:
    - legal_review_score
    - implementation_feasibility_score
    - risk_coverage_completeness